# ========================================
# 1. CARTSERVICE - Modified for Vault + PostgreSQL
# ========================================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
      annotations:
        # Vault Agent Sidecar Injection
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "cartservice-role"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/cartservice-role"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/cartservice-role" -}}
          export DB_HOST="YOUR_RDS_ENDPOINT.rds.amazonaws.com"
          export DB_PORT="5432"
          export DB_NAME="cart_db"
          export DB_USER="{{ .Data.username }}"
          export DB_PASSWORD="{{ .Data.password }}"
          {{- end -}}
    spec:
      serviceAccountName: cartservice-sa
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: harshakoppu945/cartservice:latest
        ports:
        - containerPort: 7070
        command: ["/bin/sh", "-c"]
        args:
          - source /vault/secrets/db-creds && /app/cartservice
        env:
        # Remove REDIS_ADDR - now using PostgreSQL
        - name: PORT
          value: "7070"
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
        readinessProbe:
          initialDelaySeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070
