apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "cartservice-role"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/cartservice-role"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/cartservice-role" -}}
          export DB_HOST="REPLACE_WITH_YOUR_RDS_ENDPOINT"
          export DB_PORT="5432"
          export DB_NAME="cart_db"
          export DB_USER="{{ .Data.username }}"
          export DB_PASSWORD="{{ .Data.password }}"
          {{- end -}}
    spec:
      serviceAccountName: cartservice-sa
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: harshakoppu945/cartservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc
          containerPort: 7070
        command: ["/bin/sh", "-c"]
        args:
          - |
            for i in $(seq 1 15); do
              [ -s /vault/secrets/db-creds ] && break || sleep 1
            done
            source /vault/secrets/db-creds
            exec /app/cartservice
        env:
        - name: PORT
          value: "7070"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070