apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkoutservice-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "checkoutservice-role"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/checkoutservice-role"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/checkoutservice-role" -}}
          export DB_HOST="micro-eks-postgresql.cjewwg2cazii.ap-south-1.rds.amazonaws.com"
          export DB_PORT="5432"
          export DB_NAME="checkout_db"
          export DB_USER="{{ .Data.username }}"
          export DB_PASSWORD="{{ .Data.password }}"
          {{- end -}}
    spec:
      serviceAccountName: checkoutservice-sa
      terminationGracePeriodSeconds: 30
      containers:
      - name: server
        image: harshakoppu945/checkoutservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5050
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Wait up to 15 seconds for vault secrets
            for i in $(seq 1 15); do
              [ -s /vault/secrets/db-creds ] && break || sleep 1
            done
            
            # Check if file exists
            if [ ! -f /vault/secrets/db-creds ]; then
              echo "ERROR: Vault secrets file not found"
              exit 1
            fi
            
            # Source credentials
            source /vault/secrets/db-creds
            
            # Verify credentials loaded
            if [ -z "$DB_USER" ] || [ -z "$DB_PASSWORD" ]; then
              echo "ERROR: DB credentials not loaded"
              exit 1
            fi
            
            echo "DB credentials loaded successfully"
            
            # Start application
            exec /app/checkoutservice
        env:
        - name: PORT
          value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"
        - name: PAYMENT_SERVICE_ADDR
          value: "paymentservice:50051"
        - name: EMAIL_SERVICE_ADDR
          value: "emailservice:5000"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5050"]
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5050"]
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050