apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkoutservice-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "checkoutservice-role"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/checkoutservice-role"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/checkoutservice-role" -}}
          export DB_HOST="REPLACE_WITH_YOUR_RDS_ENDPOINT"
          export DB_PORT="5432"
          export DB_NAME="checkout_db"
          export DB_USER="{{ .Data.username }}"
          export DB_PASSWORD="{{ .Data.password }}"
          {{- end -}}
    spec:
      serviceAccountName: checkoutservice-sa
      containers:
      - name: server
        image: harshakoppu945/checkoutservice:latest
        ports:
        - containerPort: 5050
        command: ["/bin/sh", "-c"]
        args:
          - |
            for i in $(seq 1 15); do
              [ -s /vault/secrets/db-creds ] && break || sleep 1
            done
            source /vault/secrets/db-creds
            exec /app/checkoutservice
        env:
        - name: PORT
          value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"
        - name: PAYMENT_SERVICE_ADDR
          value: "paymentservice:50051"
        - name: EMAIL_SERVICE_ADDR
          value: "emailservice:5000"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5050"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5050"]
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050