apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "paymentservice-role"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/paymentservice-role"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/paymentservice-role" -}}
          export DB_HOST="micro-eks-postgresql.cjewwg2cazii.ap-south-1.rds.amazonaws.com"
          export DB_PORT="5432"
          export DB_NAME="payment_db"
          export DB_USER="{{ .Data.username }}"
          export DB_PASSWORD="{{ .Data.password }}"
          {{- end -}}
    spec:
      serviceAccountName: paymentservice-sa
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: harshakoppu945/paymentservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc
          containerPort: 50051
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Wait up to 15 seconds for vault secrets
            for i in $(seq 1 15); do
              [ -s /vault/secrets/db-creds ] && break || sleep 1
            done
            
            # Check if file exists and is readable
            if [ ! -f /vault/secrets/db-creds ]; then
              echo "ERROR: Vault secrets file not found at /vault/secrets/db-creds"
              exit 1
            fi
            
            # Source the credentials
            source /vault/secrets/db-creds
            
            # Verify required variables are set
            if [ -z "$DB_USER" ] || [ -z "$DB_PASSWORD" ]; then
              echo "ERROR: DB credentials not properly loaded"
              exit 1
            fi
            
            echo "Successfully loaded DB credentials for user: $DB_USER"
            
            # Start the application
            exec /app/paymentservice
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051