# ========================================
# 4. PAYMENTSERVICE - Modified for Vault + PostgreSQL
# ========================================
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::YOUR_ACCOUNT_ID:role/paymentservice-irsa-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "paymentservice-role"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/paymentservice-role"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/paymentservice-role" -}}
          export DB_HOST="YOUR_RDS_ENDPOINT.rds.amazonaws.com"
          export DB_PORT="5432"
          export DB_NAME="payment_db"
          export DB_USER="{{ .Data.username }}"
          export DB_PASSWORD="{{ .Data.password }}"
          {{- end -}}
    spec:
      serviceAccountName: paymentservice-sa
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: harshakoppu945/paymentservice:latest
        ports:
        - containerPort: 50051
        command: ["/bin/sh", "-c"]
        args:
          - source /vault/secrets/db-creds && /app/paymentservice
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
