# ========================================
# 3. PRODUCTCATALOGSERVICE - Modified for Vault + PostgreSQL
# ========================================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "productcatalogservice-role"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/productcatalogservice-role"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/productcatalogservice-role" -}}
          export DB_HOST="YOUR_RDS_ENDPOINT.rds.amazonaws.com"
          export DB_PORT="5432"
          export DB_NAME="product_db"
          export DB_USER="{{ .Data.username }}"
          export DB_PASSWORD="{{ .Data.password }}"
          {{- end -}}
    spec:
      serviceAccountName: productcatalogservice-sa
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: harshakoppu945/productcatalogservice:latest
        ports:
        - containerPort: 3550
        command: ["/bin/sh", "-c"]
        args:
          - source /vault/secrets/db-creds && /app/productcatalogservice
        env:
        - name: PORT
          value: "3550"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550
